<?php

declare(strict_types=1);

namespace App\Presentation\StaticPage;

use Nette;


final class StaticPagePresenter extends Nette\Application\UI\Presenter
{
    protected function beforeRender()
    {
        parent::beforeRender(); // TODO: Change the autogenerated stub
    }

    public function actionDefault(?string $url = ''): void
    {

        $this->template->url = $url;
    }

    public function formatTemplateFiles(): array
    {
        $url = $this->getParameter('url') ?? 'home';

        return [
            __DIR__ . "/default-$url.latte",
            __DIR__ . "/default.latte",
        ];
    }
}
