<?php

declare(strict_types=1);

namespace App\Presentation\StaticPage;

use Nette;


final class StaticPagePresenter extends Nette\Application\UI\Presenter
{
    protected function beforeRender()
    {
        parent::beforeRender(); // TODO: Change the autogenerated stub
    }


}
